# Get all user queries
GET http://localhost:8000/user-queries

###

#Create a new user query
POST http://localhost:8000/user-queries
Content-Type: application/json

{
  "query": "how blockchain works?"
}

###

# base on response from  previous step, get the task_id
GET http://localhost:8000/tasks/2f2f9040-3cb6-4df8-8ae3-09b4ba58371d

###

# clarrify context
PUT http://localhost:8000/tasks/2f2f9040-3cb6-4df8-8ae3-09b4ba58371d/context
Content-Type: application/json
###

# when context is sufficient, analyze the task
POST http://localhost:8000/tasks/{task_id}/analyze
